// Code generated by hertz generator.

package user

import (
	"context"

	user "github.com/Zhou-jw/xzdp-starter/src/biz/model/api/user"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"log"
)

// SendCode .
// @router /api/user/code [POST]
func SendCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.SendCodeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &user.SendCodeResponse{
			Code:    consts.StatusBadRequest, // 400错误码
			Msg: err.Error(),             // 错误信息
		}
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	verifyCode := "987654"

	resp := &user.SendCodeResponse{
		Code:    consts.StatusOK,          // 200成功码
		Msg: "Code sent successfully", // 提示信息
		Data: verifyCode,
	}

	c.JSON(consts.StatusOK, resp)
}

// SmsLogin .
// @router /api/user/login [POST]
func SmsLogin(ctx context.Context, c *app.RequestContext) {
	var req user.SmsLoginRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		resp := &user.SmsLoginResponse{
			Code: consts.StatusBadRequest, // 400错误码
			Msg:  err.Error(),             // 错误信息
		}
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	// check sms code
	valid, _ := checkSmsCode(req.Phone, req.SmsCode)
	if !valid {
		c.String(consts.StatusUnauthorized, "Invalid SMS code")
		return
	}

	resp := new(user.SmsLoginResponse)
	resp.Msg = "Login successfully"

	c.JSON(consts.StatusOK, resp)
}

func checkSmsCode(phone string, code string) (bool, error) {
	log.Println("Checking SMS code for phone:", phone, "code:", code)
	return true, nil
}

// UserMe .
// @router /api/user/me [GET]
func UserMe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserMeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UserMeResponse)

	c.JSON(consts.StatusOK, resp)
}
