// Code generated by hertz generator.

package user

import (
	"context"
	"log"

	// "log"

	// "github.com/Zhou-jw/xzdp-starter/src/biz/dal/db"
	"github.com/Zhou-jw/xzdp-starter/src/biz/middleware/redis"
	user "github.com/Zhou-jw/xzdp-starter/src/biz/model/api/user"
	service "github.com/Zhou-jw/xzdp-starter/src/biz/service/user"

	// "github.com/Zhou-jw/xzdp-starter/src/pkg/errno"
	"github.com/Zhou-jw/xzdp-starter/src/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SendCode .
// @router /api/user/code [POST]
func SendCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.SendCodeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &user.SendCodeResponse{
			Code: consts.StatusBadRequest, // 400错误码
			Msg:  err.Error(),             // 错误信息
		}
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	verifyCode := "987654"
	redis.AddSmsCode(req.Phone, verifyCode)

	c.JSON(consts.StatusOK, user.SendCodeResponse{
		Code: consts.StatusOK,          // 200成功码
		Msg:  "Code sent successfully", // 提示信息
		Data: verifyCode,
	})
}

// SmsLogin .
// @router /api/user/login [POST]
func SmsLogin(ctx context.Context, c *app.RequestContext) {
	token := c.GetString("token")
	user_id := c.GetInt64("current_user_id")
	c.JSON(consts.StatusOK, user.SmsLoginResponse{
		Code:    consts.StatusOK,
		Msg:     "Login successful",
		Token:   token,
		UserID:  user_id,
		Success: true,
	})
}

// UserMe .
// @router /api/user/me [GET]
func UserMe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserMeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)

		c.JSON(consts.StatusOK, user.UserMeResponse{
			Code:    resp.StatusCode,
			Msg:     resp.StatusMsg,
			Success: false,
		})
		return
	}

	u, err := service.NewUserService(ctx, c).UserInfo(&req)
	log.Printf("/user/me: user id:%d", u.ID)

	resp := utils.BuildBaseResp(err)
	c.JSON(consts.StatusOK, user.UserMeResponse{
		Code:    resp.StatusCode,
		Msg:     resp.StatusMsg,
		Phone:   u.Phone,
		ID:      u.ID,
		Success: true,
	})
}
