// Code generated by hertz generator.

package user

import (
	jwtmw "github.com/Zhou-jw/xzdp-starter/src/middleware/jwt_mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _smsloginMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		jwtmw.JwtMiddleware.LoginHandler, // 在登录接口上使用JWT中间件，自动处理JWT验证和用户信息提取
	}
}
