// Code generated by hertz generator.

package main

import (
	"context"

	config "github.com/Zhou-jw/xzdp-starter/config"
	app "github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts(config.GetConf().Hertz.Address))
	excludedPaths := []string{
		"/shop",
		"/voucher",
		"/shop-type",
		"/upload",
		"/blog/hot",
		"/user/code",
		"/user/login",
		"/follow",
		"/imgs",
		"/message",
		"/blog",
	}

	h.Use(func(ctx context.Context, c *app.RequestContext) {
		path := string(c.Request.Path())
		for i := 0; i < len(excludedPaths); i++ {
			if len(path) < len(excludedPaths[i]) {
				continue
			}
			if path[:len(excludedPaths[i])] == excludedPaths[i] {
				return
			}
		}
	})

	register(h)
	h.Spin()
}
