// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api_user "github.com/Zhou-jw/xzdp-starter/src/biz/router/api/user"
	common "github.com/Zhou-jw/xzdp-starter/src/biz/router/common"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	common.Register(r)

	api_user.Register(r)

}
